export const WEBSERVER_DEFAULT_POLICIES = {
  tomcat: [
    { key: 'tomcat_unavailable', name: 'Tomcat实例不可用', type: 'realtime_metric', metric: 'tomcat_server_up', operator: '==', threshold: 0, level: 'critical', period: 60, times: 1, mode: 'core', enabled: true, expr: 'tomcat_server_up == 0', template: '实例不可用' },
    { key: 'tomcat_thread_busy_high', name: 'Tomcat工作线程占用偏高', type: 'periodic_metric', metric: 'currentThreadsBusy', operator: '>', threshold: 80, level: 'warning', period: 180, times: 2, mode: 'core', enabled: true, expr: '(maxThreads > 0) && ((currentThreadsBusy / maxThreads) * 100 > 80)', template: '工作线程占用偏高' },
    { key: 'tomcat_thread_busy_critical', name: 'Tomcat工作线程占用过高', type: 'periodic_metric', metric: 'currentThreadsBusy', operator: '>', threshold: 90, level: 'critical', period: 120, times: 1, mode: 'core', enabled: true, expr: '(maxThreads > 0) && ((currentThreadsBusy / maxThreads) * 100 > 90)', template: '工作线程占用过高' },
    { key: 'tomcat_connector_connections_high', name: 'Tomcat连接数偏高', type: 'periodic_metric', metric: 'connectionCount', operator: '>', threshold: 5000, level: 'warning', period: 300, times: 2, mode: 'core', enabled: true, expr: 'connectionCount > 5000', template: '连接数偏高' },
    { key: 'tomcat_request_max_time_high', name: 'Tomcat请求最大耗时偏高', type: 'periodic_metric', metric: 'maxTime', operator: '>', threshold: 1000, level: 'warning', period: 180, times: 2, mode: 'core', enabled: true, expr: 'maxTime > 1000', template: '请求最大耗时偏高' },
    { key: 'tomcat_request_max_time_critical', name: 'Tomcat请求最大耗时过高', type: 'periodic_metric', metric: 'maxTime', operator: '>', threshold: 3000, level: 'critical', period: 120, times: 1, mode: 'core', enabled: true, expr: 'maxTime > 3000', template: '请求最大耗时过高' },
    { key: 'tomcat_heap_usage_high', name: 'Tomcat堆内存使用率偏高', type: 'periodic_metric', metric: 'heap_used', operator: '>', threshold: 80, level: 'warning', period: 300, times: 2, mode: 'core', enabled: true, expr: '(heap_max > 0) && ((heap_used / heap_max) * 100 > 80)', template: '堆内存使用率偏高' },
    { key: 'tomcat_heap_usage_critical', name: 'Tomcat堆内存使用率过高', type: 'periodic_metric', metric: 'heap_used', operator: '>', threshold: 90, level: 'critical', period: 300, times: 1, mode: 'core', enabled: true, expr: '(heap_max > 0) && ((heap_used / heap_max) * 100 > 90)', template: '堆内存使用率过高' },
    { key: 'tomcat_error_count_burst', name: 'Tomcat错误请求累计偏多', type: 'periodic_metric', metric: 'errorCount', operator: '>', threshold: 1000, level: 'warning', period: 300, times: 2, mode: 'extended', enabled: false, expr: 'errorCount > 1000', template: '错误请求累计偏多' },
    { key: 'tomcat_pending_finalization_high', name: 'Tomcat对象终结队列积压', type: 'periodic_metric', metric: 'ObjectPendingFinalizationCount', operator: '>', threshold: 100, level: 'warning', period: 300, times: 2, mode: 'extended', enabled: false, expr: 'ObjectPendingFinalizationCount > 100', template: '对象终结队列积压' },
    { key: 'tomcat_uptime_short', name: 'Tomcat运行时长过短', type: 'periodic_metric', metric: 'Uptime', operator: '<', threshold: 3600000, level: 'warning', period: 600, times: 1, mode: 'extended', enabled: false, expr: 'Uptime < 3600000', template: '运行时长过短' }
  ],
  jetty: [
    { key: 'jetty_unavailable', name: 'Jetty实例不可用', type: 'realtime_metric', metric: 'jetty_server_up', operator: '==', threshold: 0, level: 'critical', period: 60, times: 1, mode: 'core', enabled: true, expr: 'jetty_server_up == 0', template: '实例不可用' },
    { key: 'jetty_server_state_abnormal', name: 'Jetty服务状态异常', type: 'realtime_metric', metric: 'state', operator: '==', threshold: 0, level: 'critical', period: 60, times: 1, mode: 'core', enabled: true, expr: "state != 'STARTED' && state != 'RUNNING'", template: '服务状态异常' },
    { key: 'jetty_thread_busy_high', name: 'Jetty工作线程占用偏高', type: 'periodic_metric', metric: 'busyThreads', operator: '>', threshold: 80, level: 'warning', period: 180, times: 2, mode: 'core', enabled: true, expr: '(maxThreads > 0) && ((busyThreads / maxThreads) * 100 > 80)', template: '工作线程占用偏高' },
    { key: 'jetty_thread_busy_critical', name: 'Jetty工作线程占用过高', type: 'periodic_metric', metric: 'busyThreads', operator: '>', threshold: 90, level: 'critical', period: 120, times: 1, mode: 'core', enabled: true, expr: '(maxThreads > 0) && ((busyThreads / maxThreads) * 100 > 90)', template: '工作线程占用过高' },
    { key: 'jetty_thread_queue_high', name: 'Jetty线程池排队积压偏高', type: 'periodic_metric', metric: 'queueSize', operator: '>', threshold: 200, level: 'warning', period: 180, times: 2, mode: 'core', enabled: true, expr: 'queueSize > 200', template: '线程池排队积压偏高' },
    { key: 'jetty_idle_threads_low', name: 'Jetty空闲线程过少', type: 'periodic_metric', metric: 'idleThreads', operator: '<', threshold: 2, level: 'warning', period: 180, times: 2, mode: 'extended', enabled: false, expr: 'idleThreads < 2', template: '空闲线程过少' },
    { key: 'jetty_heap_usage_high', name: 'Jetty堆内存使用率偏高', type: 'periodic_metric', metric: 'heap_used', operator: '>', threshold: 80, level: 'warning', period: 300, times: 2, mode: 'core', enabled: true, expr: '(heap_max > 0) && ((heap_used / heap_max) * 100 > 80)', template: '堆内存使用率偏高' },
    { key: 'jetty_heap_usage_critical', name: 'Jetty堆内存使用率过高', type: 'periodic_metric', metric: 'heap_used', operator: '>', threshold: 90, level: 'critical', period: 300, times: 1, mode: 'core', enabled: true, expr: '(heap_max > 0) && ((heap_used / heap_max) * 100 > 90)', template: '堆内存使用率过高' },
    { key: 'jetty_gc_time_high', name: 'Jetty GC累计耗时偏高', type: 'periodic_metric', metric: 'CollectionTime', operator: '>', threshold: 300000, level: 'warning', period: 600, times: 2, mode: 'extended', enabled: false, expr: 'CollectionTime > 300000', template: 'GC累计耗时偏高' },
    { key: 'jetty_pending_finalization_high', name: 'Jetty对象终结队列积压', type: 'periodic_metric', metric: 'ObjectPendingFinalizationCount', operator: '>', threshold: 100, level: 'warning', period: 300, times: 2, mode: 'extended', enabled: false, expr: 'ObjectPendingFinalizationCount > 100', template: '对象终结队列积压' },
    { key: 'jetty_uptime_short', name: 'Jetty运行时长过短', type: 'periodic_metric', metric: 'Uptime', operator: '<', threshold: 3600000, level: 'warning', period: 600, times: 1, mode: 'extended', enabled: false, expr: 'Uptime < 3600000', template: '运行时长过短' }
  ]
} as const
