"""add notification is_archived column

Revision ID: b3bf7a0c3253
Revises: 
Create Date: 2026-02-20 09:36:30.953418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bf7a0c3253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ci_relations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    op.create_table('ci_relations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_ci_id', sa.INTEGER(), nullable=False),
    sa.Column('target_ci_id', sa.INTEGER(), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_ci_id'], ['ci_instances.id'], ),
    sa.ForeignKeyConstraint(['target_ci_id'], ['ci_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ci_id', 'target_ci_id', 'relation_type', name='unique_ci_relation')
    )
    # ### end Alembic commands ###
