"""add department role_ids field

Revision ID: c0d94d03bf29
Revises: b3bf7a0c3253
Create Date: 2026-02-20 15:56:05.858746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d94d03bf29'
down_revision = 'b3bf7a0c3253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('role_ids')

    # ### end Alembic commands ###
