"""添加自定义视图索引

Revision ID: e6f7g8h9i0j1
Revises: a1b2c3d4e5f6
Create Date: 2026-02-24 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f7g8h9i0j1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 为 custom_view_nodes 表添加索引
    op.create_index('ix_custom_view_nodes_view_id', 'custom_view_nodes', ['view_id'])
    op.create_index('ix_custom_view_nodes_parent_id', 'custom_view_nodes', ['parent_id'])
    op.create_index('ix_custom_view_nodes_is_active', 'custom_view_nodes', ['is_active'])
    
    # 创建复合索引
    op.create_index('ix_view_node_parent', 'custom_view_nodes', ['view_id', 'parent_id'])
    op.create_index('ix_view_node_active', 'custom_view_nodes', ['view_id', 'is_active'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index('ix_view_node_active', table_name='custom_view_nodes')
    op.drop_index('ix_view_node_parent', table_name='custom_view_nodes')
    op.drop_index('ix_custom_view_nodes_is_active', table_name='custom_view_nodes')
    op.drop_index('ix_custom_view_nodes_parent_id', table_name='custom_view_nodes')
    op.drop_index('ix_custom_view_nodes_view_id', table_name='custom_view_nodes')
    
    # ### end Alembic commands ###
